In [1]:
import numpy as np
arr = np.array([10,20,30,40,50])
print(arr)
print(type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np


arr = np.array([[1, 2, 3], [4, 5, 6]])
print("No. of dimensions: ", arr.ndim)
print("Shape of array: ", arr.shape)
print("Size of array: ", arr.size)
print("Array stored element of types: ", arr.dtype)
print("Length of one array element in bytes: ", arr.itemsize)
print("Array's data: ", arr.data)


No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stored element of types:  int32
Length of one array element in bytes:  4
Array's data:  <memory at 0x000001499B5F2740>


In [7]:
# Converting 1D to 4D using reshape()
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(3,4)
print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [1]:
# flatten in Python
import numpy as np
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],[[7,8,9],[10,11,12]]])
flattened_array = arr3D.flatten() #4D to 1D conversion
flattened_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [17]:
# nd.transpose function (columns to rows and vice versa)
import numpy as np
arr2d = np.array([[1,2,3],[4,5,6]])
transposed_array = arr2d.transpose()
transposed_array

array([[1, 4],
       [2, 5],
       [3, 6]])

# Numpy Arithmetic statistical function

## Aritmetical and statistical operations (Addition, subtraction, multiply, divide, power of() )

In [18]:
#Addition in array 
a = np.array([10,20,30])
b = np.array([30,20,10])
c = np.add(a,b)
print(c)

[40 40 40]


In [20]:
#Subtraction in array 
a = np.array([10,20,30])
b = np.array([30,20,10])
c = np.subtract(a,b)
print(c)

[-20   0  20]


In [21]:
#multiplication in array 
a = np.array([10,20,30])
b = np.array([30,20,10])
c = np.multiply(a,b)
print(c)

[300 400 300]


In [22]:
#Division in array 
a = np.array([10,20,30])
b = np.array([30,20,10])
c = np.divide(a,b)
print(c)

[0.33333333 1.         3.        ]


## Calculating Mean ,Median Std Deviation and variance

In [28]:
#Median in array 
a = np.array([[10,20,30],[30,20,10]])
np.median(a)
print(np.median(a))

20.0


In [27]:
#Mean in array 
np.mean(a)
print(np.mean(a))

20.0


In [25]:
#Standard Deviation in array 
np.std(a)
print(np.std(a))

8.16496580927726


In [26]:
#Variance in array 
np.var(a)
print(np.var(a))

66.66666666666667
