In [ ]:
Covariance is a measure of the relationship between two random variables and the extent to which they change together.
 If the greater values of one variable mainly correspond with the greater values of the other variable,
 and the same holds for the lesser values, the covariance is positive. In the opposite case, when the greater 
 values of one variable mainly correspond to the lesser values of the other, the covariance is negative. 
 Covariance is calculated as the expected value of the product of the deviations of two random variables from their means.
 

In [5]:
import numpy as np

# Define the array
array = np.array([[4,3,2], [10,1,0]])

# Calculate the mean
mean = np.mean(array)

# Calculate the median
median = np.median(array)

# Calculate the mode
mode = np.bincount(array.flatten()).argmax()



print("Mean: ", mean)
print("Median: ", median)
print("Mode: ", mode)

Mean:  3.3333333333333335
Median:  2.5
Mode:  0


### standard deviation = √variance
### standard error = standard deviation / √n
### mean = (Σxi) / n
### median = (n+1)/2 th value when xi is sorted
### mode = most frequently occurring value in xi

#### variance is related with one attribute but it deals with how a single attribute affects the overall outcome, whereas co-variance is connected to two attributes and it measures how the relationship between these two attributes impacts the result.

### Co-variance Thoughts

## Positive Co-variance
When two attributes have a positive co-variance, it means that as one attribute increases, the other attribute also tends to increase. This relationship can be beneficial in certain situations, such as:

* In finance, a positive co-variance between stock prices and economic growth can indicate a healthy economy.
* In marketing, a positive co-variance between advertising spend and sales can indicate an effective marketing strategy.

## Negative Co-variance
When two attributes have a negative co-variance, it means that as one attribute increases, the other attribute tends to decrease. This relationship can be beneficial in certain situations, such as:

* In finance, a negative co-variance between stock prices and interest rates can indicate a stable economy.
* In healthcare, a negative co-variance between disease incidence and vaccination rates can indicate an effective public health strategy.

## Zero Co-variance
When two attributes have a zero co-variance, it means that there is no linear relationship between the two attributes. This can be beneficial in certain situations, such as:

* In finance, a zero co-variance between stock prices and inflation rates can indicate a stable economy.
* In engineering, a zero co-variance between system inputs and outputs can indicate a well-designed system.

In conclusion, understanding co-variance is crucial in making informed decisions in various fields. By analyzing the relationship between attributes, we can identify patterns and trends that can help us make better predictions and decisions.

#### ## Correlation and Coefficient

Correlation is a statistical measure that calculates the strength and direction of the linear relationship between two continuous variables. The correlation coefficient is a numerical value that ranges from -1 to 1, where:

* 1 indicates a perfect positive linear relationship
* -1 indicates a perfect negative linear relationship
* 0 indicates no linear relationship

The correlation coefficient is often denoted by the Greek letter rho (ρ) and can be calculated using the following formula:

ρ = cov(X, Y) / (σX * σY)

where:

* cov(X, Y) is the covariance between variables X and Y
* σX and σY are the standard deviations of variables X and Y, respectively

There are several types of correlation coefficients, including:

* Pearson's correlation coefficient (r): measures the linear relationship between two continuous variables
* Spearman's rank correlation coefficient (ρ): measures the monotonic relationship between two continuous variables
* Kendall's tau correlation coefficient (τ): measures the concordance between two continuous variables

In Python, you can calculate the correlation coefficient using the `numpy` library:
```python
import numpy as np

# Define two arrays of data
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 3, 5, 7, 11])

# Calculate the correlation coefficient
corr_coef = np.corrcoef(x, y)[0, 1]

print("Correlation coefficient:", corr_coef)
```
This code calculates the Pearson's correlation coefficient between the two arrays `x` and `y`.

# _______________________________________________________________________________________________________________________

## 3.String functions in Numpy 
### Theory
NumPy provides several string functions to manipulate and operate on strings. These functions can be used to perform various operations such as concatenation, comparison, and searching.

### Examples
```python
import numpy as np

# 1. np.char.add()
# This function is used to concatenate two strings.
print(np.char.add(['Hello,'], [' how are you?']))

# 2. np.char.multiply()
# This function is used to repeat a string.
print(np.char.multiply('Hello ', 3))

# 3. np.char.center()
# This function is used to center a string.
print(np.char.center('Hello', 10, '*'))

# 4. np.char.capitalize()
# This function is used to capitalize the first letter of a string.
print(np.char.capitalize('hello'))

# 5. np.char.title()
# This function is used to capitalize the first letter of each word in a string.
print(np.char.title('hello world'))

# 6. np.char.lower()
# This function is used to convert a string to lowercase.
print(np.char.lower('HELLO'))

# 7. np.char.upper()
# This function is used to convert a string to uppercase.
print(np.char.upper('hello'))

# 8. np.char.split()
# This function is used to split a string into substrings.
print(np.char.split('hello world', sep=' '))

# 9. np.char.strip()
# This function is used to remove leading and trailing characters from a string.
print(np.char.strip('   hello   ', ' '))

# 10. np.char.join()
# This function is used to join two or more strings.
print(np.char.join(['hello', 'world'], sep=' '))
```

### String Concatenation 

String concatenation is the process of combining two or more strings into a single string. This can be achieved using various methods, including the use of operators, functions, or formatting techniques.

#### Using the `+` Operator

The `+` operator is the most common method for concatenating strings in many programming languages.


# Example 1: Concatenating two strings using the `+` operator
str1 = "Hello, "
str2 = "world!"
result = str1 + str2
print(result)  # Output: "Hello, world!"


#### Using the `join()` Method

The `join()` method is another way to concatenate strings. It takes an iterable of strings as an argument and returns a single string with the elements joined together.


# Example 2: Concatenating multiple strings using the `join()` method
strings = ["Hello", ", ", "world", "!"]
result = "".join(strings)
print(result)  # Output: "Hello, world!"
```

#### Using F-Strings (Formatted Strings)

F-strings are a feature in Python that allows you to embed expressions inside string literals, using the `f` prefix.


# Example 3: Concatenating strings using f-strings
name = "John"
age = 30
result = f"My name is {name} and I am {age} years old."
print(result)  # Output: "My name is John and I am 30 years old."
```

#### Using the `format()` Method

The `format()` method is another way to concatenate strings by embedding expressions inside string literals.


# Example 4: Concatenating strings using the `format()` method
name = "John"
age = 30
result = "My name is {} and I am {} years old.".format(name, age)
print(result)  # Output: "My name is John and I am 30 years old."
```

#### Replacing old array element with the new array element

In [7]:
str = "Hello How are You"
print (str)
z = np.char.replace(str, 'hello', 'hi')
print(z)

Hello How are You
Hello How are You


### Converting all lowerccase charcaters in a string to uppercase and vice versa

In [12]:
# Example 1: Using swapcase() method
str1 = "Hello How are You"
result1 = str1.swapcase()
print(result1)  # Output: hELLO hOW ARE yOU

# Example 2: Using swapcase() method with a different string
str2 = "Python is FUN!"
result2 = str2.swapcase()
print(result2)  # Output: pYTHON IS fun!

hELLO hOW ARE yOU
pYTHON IS fun!


#### Indexing
Indexing is a data structure technique that allows for efficient querying and retrieval of data. It involves creating a data structure that facilitates quick lookup, insertion, and deletion of data.

There are several types of indexing, including:

1. **Hash Indexing**: uses a hash function to map keys to specific locations in an array.
2. **B-Tree Indexing**: uses a self-balancing search tree to keep data sorted and allow for efficient insertion and deletion.
3. **Bitmap Indexing**: uses a bitmap to represent the presence or absence of a value in a column.
4. **Full-Text Indexing**: used for full-text search, allowing for efficient querying of text data.
5. **Clustered Indexing**: reorders the physical records of the table according to the index keys.
6. **Non-Clustered Indexing**: creates a separate data structure that contains the index keys and pointers to the corresponding records.
7. **Composite Indexing**: combines multiple columns into a single index.
8. **Function-Based Indexing**: uses a function to compute the index value.
9. **Partitioned Indexing**: divides the index into smaller partitions based on a specific criteria.



#### Accesing elements in 1D,2D,3D arrays


# 1D Array

In [22]:

array_1d = [1, 2, 3, 4, 5,10]

# Accessing elements in 1D array
print(array_1d[0])  # Output: 1
print(array_1d[-1])  # Output: 5




1
10
[2, 3]
[3, 4, 5, 10]


# 2D Array


In [9]:
array_2d = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# Accessing elements in 2D array
print(array_2d[0][0])  # Output: 1
print(array_2d[1][1])  # Output: 5
print(array_2d[2][2])  # Output: 9
print(array_2d[0][1:3])  # Output: [2, 3]
print(array_2d[1:])  # Output: [[4, 5, 6], [7, 8, 9]]



1
5
9
[2, 3]
[[4, 5, 6], [7, 8, 9]]


# 3D Array


In [13]:
array_3d = [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]

# Accessing elements in 3D array
print(array_3d[0][0][0])  # Output: 1
print(array_3d[1][1][1])  # Output: 11
print(array_3d[0][1][2])  # Output: 6
print(array_3d[0][0][1:3])  # Output: [2, 3]
print(array_3d[1][1:])  # Output: [[10, 11, 12]]

1
11
6
[2, 3]
[[10, 11, 12]]


## ________________________________________________________________________________________________________________________________________________________
## Numpy Array Slicing

### Slicing in 1D array

In [24]:
### import numpy as np

# 1D Array
array_1d = np.array([1, 2, 3, 4, 5, 10])

# Slicing 1D array
print(array_1d[1:4])  # Output: [2 3 4]
print(array_1d[:3])   # Output: [1 2 3]
print(array_1d[3:])   # Output: [ 4  5 10]
print(array_1d[::2])  # Output: [ 1  3  5]

[2 3 4]
[1 2 3]
[ 4  5 10]
[1 3 5]


### Slicing in 2D array

In [25]:


# 2D Array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Slicing 2D array
print(array_2d[1:, 1:])  # Output: [[5 6]
                         #          [8 9]]
print(array_2d[:2, :2])  # Output: [[1 2]
                         #          [4 5]]
print(array_2d[::2, ::2])  # Output: [[1 3]
                           #          [7 9]]



[[5 6]
 [8 9]]
[[1 2]
 [4 5]]
[[1 3]
 [7 9]]


### Slicing in 3D array

In [ ]:
# 3D Array
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

# Slicing 3D array
print(array_3d[:, :, 1:])  # Output: [[[ 2  3]
                           #           [ 5  6]]
                           #          [[ 8  9]
                           #           [11 12]]]
print(array_3d[:, 1:, :2])  # Output: [[[ 4  5]]
                            #          [[10 11]]]
print(array_3d[::2, ::2, ::2])  # Output: [[[1 3]]
                                #          [[7 9]]]

#### Example 1:use slicing to retrieve employee ratings for a team of seven employees in the first quarter from the array

In [26]:
# Assuming the array contains employee ratings for each quarter
# For simplicity, let's create a sample array with random ratings
employee_ratings = np.array([
    [4, 3, 5, 2],  # Employee 1
    [5, 4, 3, 4],  # Employee 2
    [3, 5, 4, 3],
    ])# Employee 3# Assuming the array contains employee ratings for each quarter
# For simplicity, let's create a sample array with random ratings
employee_ratings = np.array([
    [4, 3, 5, 2],  # Employee 1
    [5, 4, 3, 4],  # Employee 2
    [3, 5, 4, 3],
    ])# Employee 3# Assuming the array contains employee ratings for each quarter
# For simplicity, let's create a sample array with random ratings
employee_ratings = np.array([
    [4, 3, 5, 2],  # Employee 1
    [5, 4, 3, 4],  # Employee 2
    [3, 5, 4, 3],  # Employee 3
])
# Calculate the mean rating for each employee
mean_ratings = np.mean(employee_ratings)

# Print the mean ratings for each employee
print("Mean ratings for each employee:")
print(mean_ratings)




Mean ratings for each employee:
3.75


### Example 2: Print the list of three subjects from the fourth index of the end


In [31]:
Books = np.array(['Physics','DS','Math','Python','Java','Cloud','C++'])
print(Books[4:])

['Java' 'Cloud' 'C++']


# Types of Slicing in Python

## 1. Basic Slicing

Basic slicing is used to extract a subset of elements from a list. The syntax for basic slicing is `list[start:stop:step]`.

```python
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9]
print(numbers[1:5])  # Output: [2, 3, 4, 5]
```

## 2. Omitting Start Index

If the start index is omitted, it defaults to 0.

```python
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9]
print(numbers[:5])  # Output: [1, 2, 3, 4, 5]
```

## 3. Omitting Stop Index

If the stop index is omitted, it defaults to the end of the list.

```python
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9]
print(numbers[5:])  # Output: [6, 7, 8, 9]
```

## 4. Omitting Both Start and Stop Index

If both start and stop index are omitted, it returns a copy of the entire list.

```python
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9]
print(numbers[:])  # Output: [1, 2, 3, 4, 5, 6, 7, 8, 9]
```

## 5. Negative Indexing

Negative indexing starts from the end of the list.

```python
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9]
print(numbers[-3:])  # Output: [7, 8, 9]
```

## 6. Step Slicing

Step slicing is used to extract every nth element from a list.

```python
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9]
print(numbers[::2])  # Output: [1, 3, 5, 7, 9]
```

## 7. Reversing a List

Reversing a list can be done by using a step of -1.

```python
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9]
print(numbers[::-1])  # Output: [9, 8, 7, 6, 5, 4, 3, 2, 1]
```