# Unit -1 : NumPy

**Instructor:** Dr. A. V. Brahmane  
**Duration:** 7 Hours  
**Objective:** This notebook will help you understand **NumPy** with hands-on coding exercises.  

 **Topics Covered:**  
1. Introduction to NumPy Arrays  
2. NumPy N-dimensional Arrays (1D, 2D, 3D)  
3. Functions to Create Arrays  
4. Combining Arrays  
5. Indexing, Slicing & Reshaping  
6. List to Array Conversion  
7. String Indexing & Slicing  
8. Operations on Arrays (Arithmetic & Logical)  
9. Practice Exercises for Students  

 **How to use this notebook?**  
- Read the explanation first.  
- Run the Python code.  
- Try modifying and experimenting with the code.  
- Solve the practice exercises provided.  

Let's get started!


## 1️⃣ Introduction to NumPy

NumPy (Numerical Python) is a library used for numerical computing in Python. It provides fast and memory-efficient arrays and mathematical functions.

In [1]:
import numpy as np
print('NumPy is successfully imported!')

NumPy is successfully imported!


### 📝 Syntax Breakdown
1. `import numpy as np` → Imports NumPy with an alias `np`.
2. `print('NumPy is successfully imported!')` → Checks if NumPy is installed properly.

### 🏋️‍♂️ Practice Exercise
✅ **Practice:** Try to import NumPy and check its version using `np.__version__`.

## 2️⃣ NumPy N-dimensional Arrays (1D, 2D, 3D)

NumPy arrays can be 1D, 2D, or 3D. They are more efficient than Python lists.

In [2]:
arr1D = np.array([1, 2, 3, 4, 5])
arr2D = np.array([[1, 2, 3], [4, 5, 6]])
arr3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print('1D Array:', arr1D)
print('2D Array:\n', arr2D)
print('3D Array:\n', arr3D)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### 📝 Syntax Breakdown
1. `np.array([values])` → Creates a 1D NumPy array.
2. `np.array([[row1], [row2]])` → Creates a 2D array.
3. `np.array([[[depth1], [depth2]], [[depth3], [depth4]]])` → Creates a 3D array.

### 🏋️‍♂️ Practice Exercise
✅ **Practice:** Create a 2D array of shape (4,4) with values of your choice.

## 3️⃣ Functions to Create Arrays

NumPy provides multiple functions to create arrays efficiently.

In [3]:
zeros_array = np.zeros((3, 3))
ones_array = np.ones((2, 4))
rand_array = np.random.rand(3,3)
print('Zeros Array:\n', zeros_array)
print('Ones Array:\n', ones_array)
print('Random Array:\n', rand_array)

Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Random Array:
 [[0.86157271 0.92078278 0.80740609]
 [0.94333351 0.34123233 0.6384277 ]
 [0.44647066 0.03196724 0.12308523]]


### 📝 Syntax Breakdown
1. `np.zeros((rows, cols))` → Creates an array filled with zeros.
2. `np.ones((rows, cols))` → Creates an array filled with ones.
3. `np.random.rand(rows, cols)` → Creates an array with random values.

### 🏋️‍♂️ Practice Exercise
✅ **Practice:** Create a 5x5 identity matrix using NumPy.

## 4️⃣ Combining Arrays

We can combine multiple arrays using concatenation.

In [4]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.concatenate((a, b))
print('Concatenated Array:', c)

Concatenated Array: [1 2 3 4 5 6]


### 📝 Syntax Breakdown
1. `np.concatenate((array1, array2))` → Combines two arrays into one.

### 🏋️‍♂️ Practice Exercise
✅ **Practice:** Try combining two 2D arrays using `np.vstack()`.

## 5️⃣ Indexing, Slicing & Reshaping

NumPy allows easy indexing, slicing, and reshaping of arrays.

In [5]:
arr = np.array([10, 20, 30, 40, 50])
print('First Element:', arr[0])
print('Last 3 Elements:', arr[-3:])
reshaped = arr.reshape(5,1)
print('Reshaped Array:\n', reshaped)

First Element: 10
Last 3 Elements: [30 40 50]
Reshaped Array:
 [[10]
 [20]
 [30]
 [40]
 [50]]


### 📝 Syntax Breakdown
1. `arr[index]` → Accesses a specific element.
2. `arr[start:end]` → Extracts a slice from the array.
3. `arr.reshape(rows, cols)` → Reshapes the array.

### 🏋️‍♂️ Practice Exercise
✅ **Practice:** Reshape a (3,3) matrix into a (1,9) array.

## 6️⃣ String Indexing & Slicing

Strings in Python can be indexed and sliced just like arrays.

In [ ]:
text = 'NumPy Library'
print('First Character:', text[0])
print('Slice:', text[0:5])
print('Reverse:', text[::-1])

### 📝 Syntax Breakdown
1. `text[index]` → Access a character.
2. `text[start:end]` → Slice a substring.
3. `text[::-1]` → Reverse a string.

### 🏋️‍♂️ Practice Exercise
✅ **Practice:** Try extracting 'Library' from the string using slicing.

## 7️⃣ Operations on Arrays (Arithmetic & Logical)

NumPy supports element-wise arithmetic operations.

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print('Addition:', arr1 + arr2)
print('Multiplication:', arr1 * arr2)

### 📝 Syntax Breakdown
1. `arr1 + arr2` → Adds two arrays element-wise.
2. `arr1 * arr2` → Multiplies two arrays element-wise.

### 🏋️‍♂️ Practice Exercise
✅ **Practice:** Perform element-wise division on two NumPy arrays.